### PR TITLE
[fixme]OGP

### LINKED ISSUE #15: OGP系の設定をする

### PR DESCRIPTION
**Pull request by taea**
fixes #15 

FIXME og:url をHelper にする @fukayatsu :pray:

### CODE REVIEW

**Comment by fukayatsu** [comment]
:makasero

**Comment by taea** [comment]
:douyatteyatteruno

**Comment by taea** [comment]
:yattane

**Comment by taea** [comment]
:shipit: ?

**Comment by fukayatsu** [comment]
:ship: :dash:

**Pull request merged**
